### ISSUE TITLE
Increase in running time for fit function

### ISSUE THREAD

**Issue by aaby4373** [julianspaeth/random-survival-forest#10]
I am running a dataset that has 12K rows, with this RSF module. The fit function has been running for the past 2 days and there is no output. can someone please confirm if this is expected?

Also, how does this address an imbalanced dataset?

**Comment by julianspaeth** [comment]
Hi @aaby4373, the runtime is indeed an issue in this package. With 12k rows, you have a lot of samples and it can take quite a while. The main focus of this package was to provide an easy-to-understand algorithm here and not the runtime. However, if someone has the time to tune the runtime that would be great.

Addressing imbalanced datasets is not addressed. There might be some over-/undersampling strategies for RSF that could be implemented.
