### ISSUE TITLE
Starting code

### ISSUE THREAD

**Issue by willthd** [julianspaeth/random-survival-forest#4]
@julianspaeth 
Hi Julian.
What is x and y? also x_val and y_val?
I think you mean x and x_val are same.
And i want to know they should be dataframe not array.
Also, what type of y_val['time'] ?

If you describe dataset for x and y specifically, It would be better for everyone to understand :)

**Comment by julianspaeth** [comment]
Hi,

thanks for your feedback, I will enhance the description soon!
Unfortunately, the package is still in an early stage and I hope I'll find the time to enhance some parts soon. Sorry for the late answer, somehow I did not get a notification.

Here are the short answers to your questions:

- x is the feature matrix for the training and y are the labels for the training.
- the feature matrix is a Pandas Dataframe and can be of any size (samples x features).
- the labels are also a Pandas Dataframe (samples x 2) with the survival time in the first column and the event in the second column.
- x_val and y_val is just a dataset for validation. If you want to see how good the model performs you should test it on data that was not used for fitting the model.

I hope this is kind of helpful for now if you have further questions just let me know.

**Comment by julianspaeth** [comment]
Ah and addressing your last question:

y_val['time] is the survival time of the validation set. The concordance index is calculated based on the known survival times and events of the validation samples and the outcomes (cumulative hazard functions) of each validation sample, predicted by the Random Survival Forest model.

**Comment by willthd** [comment]
Thank you for your answer !
This package will be helpful for python user to develop survival analysis model.
I really hope it would be supplemented soon.
