### ISSUE TITLE
Memory Error:

### ISSUE THREAD

**Issue by heavycello** [julianspaeth/random-survival-forest#5]
The fit method keeps returning a Memory Error without any additional information. It looks like it is getting hung up on the oob score. This is the error code I get. I'm wondering, is there is a dataframe size that works well for you? I'm training on about 90,000 samples with about 15 feature columns. Thanks for any help you can give. 

MemoryError                               Traceback (most recent call last)
<ipython-input-28-d5a89ecfb172> in <module>
      1 timeline = range(0, 10, 1)
      2 rsf = RandomSurvivalForest(n_estimators=10, timeline=timeline, n_jobs = -1)
----> 3 rsf.fit(X_train, y_train)
      4 round(rsf.oob_score, 3)
      5 0.76

C:\ProgramData\Anaconda3\lib\site-packages\random_survival_forest\RandomSurvivalForest.py in fit(self, x, y)
     59                 self.bootstraps.append(self.bootstrap_idxs[i])
     60 
---> 61         self.oob_score = self.compute_oob_score(x, y)
     62 
     63         return self

C:\ProgramData\Anaconda3\lib\site-packages\random_survival_forest\RandomSurvivalForest.py in compute_oob_score(self, x, y)
     99         """
    100         oob_ensembles = self.compute_oob_ensembles(x)
--> 101         c = concordance_index(y_time=y.iloc[:, 0], y_pred=oob_ensembles, y_event=y.iloc[:, 1])
    102         return c
    103 

C:\ProgramData\Anaconda3\lib\site-packages\random_survival_forest\scoring.py in concordance_index(y_time, y_pred, y_event)
     11     """
     12     oob_predicted_outcome = [x.sum() for x in y_pred]
---> 13     possible_pairs = list(combinations(range(len(y_pred)), 2))
     14     concordance = 0
     15     permissible = 0

**Comment by julianspaeth** [comment]
Hey,

I never tried 90.000 samples, the highest I used was 2000. Could you try if the fit works for fewer samples, e.g. 5000?

---> 61 self.oob_score = self.compute_oob_score(x, y)
Furthermore, could you try to comment out the oob_score computation in the fit method? If this is the problem, I could separate the oob_score prediction from the fit method.

---> 13 possible_pairs = list(combinations(range(len(y_pred)), 2))
The c-index computes all possible pairs of the OOB data. Creating a list with possible pairs of the 90.000 samples could just be too much and result in a memory error.
